//
//  AsmDSL.swift
//  ReixOS — reix plugin
//
//  Created by Eliomar on 28/06/2026.
//


func fn(_ name: String, @AsmBuilder _ body: () -> [String]) -> AsmRoutine {
    AsmRoutine(name: name, lines: body())
}

/// Renders a list of routines into one `.S` file: a `.text` section, a `.global`
/// for each routine, then each routine's label followed by its body lines.
func renderAsmFile(_ routines: [AsmRoutine]) -> String {
    var s = "// Generated by the reix plugin AsmDSL — do not edit.\n\n.section .text\n"
    for r in routines { s += ".global \(r.name)\n" }
    s += "\n"
    for r in routines {
        s += "\(r.name):\n"
        for line in r.lines { s += "\(line)\n" }
        s += "\n"
    }
    return s
}

// MARK: - Instruction helpers (one assembly line each)

private let ind = "    "

func msr(_ sys: String, _ imm: Int)    -> String { "\(ind)msr \(sys), #\(imm)" }
func msr(_ sys: String, _ reg: String) -> String { "\(ind)msr \(sys), \(reg)" }
func mrs(_ reg: String, _ sys: String) -> String { "\(ind)mrs \(reg), \(sys)" }

func wfi() -> String { "\(ind)wfi" }
func wfe() -> String { "\(ind)wfe" }
func nop() -> String { "\(ind)nop" }
func isb() -> String { "\(ind)isb" }
func ret() -> String { "\(ind)ret" }

func brk(_ imm: Int)   -> String { "\(ind)brk #\(imm)" }
func b(_ label: String) -> String { "\(ind)b \(label)" }
func br(_ reg: String)  -> String { "\(ind)br \(reg)" }
func adr(_ reg: String, _ label: String) -> String { "\(ind)adr \(reg), \(label)" }

func mov(_ d: String, _ imm: Int)    -> String { "\(ind)mov \(d), #\(imm)" }
func mov(_ d: String, _ src: String) -> String { "\(ind)mov \(d), \(src)" }
func add(_ d: String, _ a: String, _ b: String) -> String { "\(ind)add \(d), \(a), \(b)" }
func orr(_ d: String, _ a: String, _ b: String) -> String { "\(ind)orr \(d), \(a), \(b)" }
func and(_ d: String, _ a: String, _ imm: Int)  -> String { "\(ind)and \(d), \(a), #\(imm)" }
func udiv(_ d: String, _ a: String, _ b: String) -> String { "\(ind)udiv \(d), \(a), \(b)" }

func ldrImm(_ reg: String, _ value: UInt64) -> String { "\(ind)ldr \(reg), =0x\(String(value, radix: 16))" }

func tlbi(_ op: String) -> String { "\(ind)tlbi \(op)" }
func ic(_ op: String)   -> String { "\(ind)ic \(op)" }
func dsb(_ opt: String) -> String { "\(ind)dsb \(opt)" }
func dmb(_ opt: String) -> String { "\(ind)dmb \(opt)" }

func label(_ name: String) -> String { "\(name):" }
func raw(_ line: String)   -> String { line }
