//
//  RXSyscallCore.swift
//  ReixOS
//
//  Created by Eliomar Alejandro Rodriguez Ferrer on 03/05/2026.
//

import ReixABI

/// Inner-shareable memory barrier (`dmb ish`), generated by the reix plugin
/// AsmDSL. Used by the SPSC `Ring` to order data writes against index updates.
@_silgen_name("dmb_ish")
public func dmbISH()

/// Orders every store already made before every store made after it, as far out
/// as a device can see.
///
/// What a driver owes the hardware before it hands anything over. A DMA buffer
/// is mapped Normal Non-Cacheable, and that attribute is about *visibility*: it
/// means a device that never looks in a cache sees what the CPU wrote without
/// any maintenance. It says nothing at all about the order the writes become
/// visible in, and Normal memory is free to be reordered - by the CPU and by the
/// compiler both.
///
/// So the descriptors have to be ordered before the index that publishes them,
/// and that index before the doorbell that says to go and read it. VirtIO
/// requires exactly this and says so: a barrier before ownership of anything is
/// transferred through an index.
///
/// Outer shareable, because the other observer is a device and not a CPU in this
/// one's inner domain. Generated by the reix plugin AsmDSL, and assembly rather
/// than Swift because a barrier is an instruction and there is no Swift for it -
/// which also makes it opaque to LLVM, so it orders the compiler as well as the
/// machine.
@_silgen_name("dma_write_barrier")
public func dmaWriteBarrier()

/// Orders every load already made before every load made after it, as far out as
/// a device can see.
///
/// The other half. Having seen a device say it is finished - a used index moving,
/// a status byte changing - this is what makes reading what it finished *with*
/// legal rather than lucky. Without it the loads of the payload may already have
/// happened, before the device wrote it.
@_silgen_name("dma_read_barrier")
public func dmaReadBarrier()

/// Write `count` bytes to a PL011 at `base`, waiting for FIFO room per byte.
///
/// Generated by the reix plugin AsmDSL, and assembly rather than Swift because
/// the FIFO-full poll has to be a volatile read. Written in Swift over a plain
/// `UnsafeMutableRawPointer` the load is loop-invariant to LLVM, which hoists it
/// out and then deletes the wait, so bytes reach the data register with no check
/// that there is room for them. `count <= 0` writes nothing.
@_silgen_name("pl011_try_read_byte")
public func pl011TryReadByte(_ base: UnsafeMutableRawPointer) -> UInt32

@_silgen_name("pl011_try_write_byte")
public func pl011TryWriteByte(
    _ base: UnsafeMutableRawPointer,
    _ byte: UInt8
) -> Bool

@_silgen_name("pl011_enable_receive")
public func pl011EnableReceive(_ base: UnsafeMutableRawPointer)

@_silgen_name("pl011_clear_receive")
public func pl011ClearReceive(_ base: UnsafeMutableRawPointer)

@_silgen_name("pl011_enable_transmit_interrupt")
public func pl011EnableTransmitInterrupt(_ base: UnsafeMutableRawPointer)

@_silgen_name("pl011_disable_transmit_interrupt")
public func pl011DisableTransmitInterrupt(_ base: UnsafeMutableRawPointer)

@_silgen_name("pl011_clear_transmit_interrupt")
public func pl011ClearTransmitInterrupt(_ base: UnsafeMutableRawPointer)

@_silgen_name("pl011_write_span")
public func pl011WriteSpan(
    _ base : UnsafeMutableRawPointer,
    _ bytes: UnsafeRawPointer,
    _ count: Int
)

/// The virtual counter, `CNTVCT_EL0`, at ~62.5 MHz on QEMU virt.
///
/// The only clock a process can read without entering the kernel: `boot.S`
/// leaves `CNTKCTL_EL1.EL0VCTEN` set, so the read is three instructions and
/// costs nothing a measurement has to subtract out. Generated by the reix
/// plugin AsmDSL, and assembly rather than Swift so that the value stays opaque
/// to LLVM: a Swift spin loop over a pure function is loop-invariant and gets
/// hoisted, then deleted.
@_silgen_name("read_virtual_counter")
public func readVirtualCounter() -> UInt64

/// Counter ticks per second, `CNTFRQ_EL0`, for turning a delta into a duration.
@_silgen_name("read_counter_frequency")
public func readCounterFrequency() -> UInt64

@_silgen_name("_asm_syscall")
private func _asm_syscall_raw(
    _ type: UInt64,
    _ a1  : UInt64,
    _ a2  : UInt64,
    _ a3  : UInt64,
    _ a4  : UInt64,
    _ a5  : UInt64,
    _ a6  : UInt64,
    _ a7  : UInt64,
) -> UInt64

@_silgen_name("_asm_recv")
public func _asm_recv_raw(
    _ number: UInt64,
    _ handle: UInt64,
    _ buffer: UnsafeMutableRawPointer
) -> UInt64

@_silgen_name("_asm_recv_timeout")
public func _asm_recv_timeout_raw(
    _ number: UInt64,
    _ handle: UInt64,
    _ ticks : UInt64,
    _ buffer: UnsafeMutableRawPointer
) -> UInt64

@_silgen_name("_asm_call")
public func _asm_call_raw(
    _ number: UInt64,
    _ handle: UInt64,
    _ tag   : UInt64,
    _ word0 : UInt64,
    _ word1 : UInt64,
    _ word2 : UInt64,
    _ word3 : UInt64,
    _ buffer: UnsafeMutableRawPointer
) -> UInt64

@_silgen_name("_asm_spawn")
public func _asm_spawn_raw(
    _ number     : UInt64,
    _ path       : UInt64,
    _ length     : UInt64,
    _ grantsPtr  : UInt64,
    _ grantsCount: UInt64,
    _ buffer     : UnsafeMutableRawPointer
) -> UInt64


public func _syscall(_ type: SyscallNumber) -> UInt64 {
    _asm_syscall_raw(type.rawValue, 0, 0, 0, 0, 0, 0, 0)
}

@discardableResult
public func _syscall(
    _ type: SyscallNumber,
    _ arg1: UInt64
) -> UInt64 {
    _asm_syscall_raw(type.rawValue, arg1, 0, 0, 0, 0, 0, 0)
}

public func _syscall(
    _ type: SyscallNumber,
    _ arg1: UInt64,
    _ arg2: UInt64
) -> UInt64 {
    _asm_syscall_raw(type.rawValue, arg1, arg2, 0, 0, 0, 0, 0)
}

/// `arg1`, `arg2`, `arg3` land in `x0`, `x1`, `x2`. `profileControl` uses them
/// for its operation, argument, and authority handle.
public func _syscall(
    _ type: SyscallNumber,
    _ arg1: UInt64,
    _ arg2: UInt64,
    _ arg3: UInt64
) -> UInt64 {
    _asm_syscall_raw(type.rawValue, arg1, arg2, arg3, 0, 0, 0, 0)
}

/// `arg4` lands in `x3`. `procStats` uses the four for a sub-operation selector,
/// its cursor, the output buffer's address, and the authority handle.
public func _syscall(
    _ type: SyscallNumber,
    _ arg1: UInt64,
    _ arg2: UInt64,
    _ arg3: UInt64,
    _ arg4: UInt64
) -> UInt64 {
    _asm_syscall_raw(type.rawValue, arg1, arg2, arg3, arg4, 0, 0, 0)
}


public func _syscall(
    _ type: SyscallNumber,
    _ arg1: UInt64,
    _ arg2: UInt64,
    _ arg3: UInt64,
    _ arg4: UInt64,
    _ arg5: UInt64,
    _ arg6: UInt64,
    _ arg7: UInt64,
) -> UInt64 {
    _asm_syscall_raw(
        type.rawValue,
        arg1,
        arg2,
        arg3,
        arg4,
        arg5,
        arg6,
        arg7
    )
}
