//
//  Uart.swift
//  ReixOS
//
//  Created by Eliomar Alejandro Rodriguez Ferrer on 19/04/2026.
//

/// The kernel's PL011, one byte at a time, with the transmit wait in assembly.
///
/// The wait cannot be written in Swift. `FR.TXFF` is a volatile read and Swift
/// has no way to spell one: over a plain pointer LLVM sees a loop-invariant
/// load, hoists it out of the wait and then drops the wait entirely, leaving
/// stores into a FIFO nothing ever checked. Userland's console lost its wait
/// exactly that way, and this loop only survived by accident, on two opaque
/// calls that happened to sit in its body (`is_mmu_enabled`, from recomputing
/// the register address, and `nop`, the pause). Removing either one is an
/// ordinary cleanup, so the loop now lives in `pl011_write_byte`, where there
/// is no Swift for the optimizer to reason about.
struct PL011UART: SerialDriver, @unchecked Sendable {

    /// Waits for transmit-FIFO room, then stores `byte` into the data register.
    /// Generated by the reix plugin AsmDSL, which is where the register map is.
    @_silgen_name("pl011_write_byte")
    private static func writeByte(
        _ base: UnsafeMutableRawPointer,
        _ byte: UInt8
    )

    /// The data register, which is at offset 0 and so is the block's base.
    ///
    /// Computed here rather than inside the routine because this is the side
    /// that knows the MMU regime: the first log lines of a boot go out before
    /// `enable_mmu` and address the UART physically, everything after it
    /// through the high-half window. Recomputed per byte rather than cached,
    /// so a `PL011UART` value outliving the switch cannot keep writing to an
    /// address that has stopped resolving.
    private var base: UnsafeMutableRawPointer {
        UnsafeMutableRawPointer(
            bitPattern: UInt(
                (Arch.MMU.isMMUEnabled() ? VirtualMemoryManager.physicalOffset : 0) &+ Kernel.platformInfo.uart.baseAddr
            )
        )!
    }


    func write(_ byte: UInt8) {
        Self.writeByte(base, byte)
    }

    func read() -> UInt8 {
        return 10
    }
}

typealias UARTQemu = PL011UART
