//
//  MMIO.swift
//  ReixOS
//
//  Created by Eliomar Alejandro Rodriguez Ferrer on 22/08/2026.
//

/// One 32-bit read of a device register. Generated by the reix plugin AsmDSL.
@_silgen_name("mmio_read32")
public func mmioRead32(_ address: UnsafeMutableRawPointer) -> UInt32

/// One 32-bit write to a device register.
@_silgen_name("mmio_write32")
public func mmioWrite32(_ address: UnsafeMutableRawPointer, _ value: UInt32)
